# Настройки сайта
title: Александр Крушин
description: Запускаю собственные проекты. До этого был директором по маркетингу портала Рамблер и директором по развитию «Афиши». Обожаю медиа, контент и новые технологии.
email: akrushin@gmail.com
baseurl: ""
url: "https://krushin.me"
permalink: /notes/:title
locale: ru_RU
logo: /images/logo.jpg

navigation:
  - title: Проекты
    url: /projects/
  - title: Заметки
    url: /notes/

author:
  name: Александр Крушин
  bio: Запускаю собственные проекты. До этого был директором по маркетингу портала <span class="rambler">Рамблер</span> и директором по развитию <span class="afisha">«Афиши»</span>. Обожаю медиа, контент и новые технологии.
  avatar: https://www.gravatar.com/avatar/173303ff8da78411c197beb08a15626f

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
